### ISSUE TITLE
Link to product notices does not resolve properly

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic-community/RunDMC#777]
Historically, the latest product notices have been reachable as http://docs.marklogic.com/copyright/legal.  When we switched to PDF-only product notices, we necessarily changed the URI of the product notices to guide/product-notices.pdf, thus breaking the magic link. This link is used in places other than internal to docs.marklogic.com, so it must continue to work.

**Comment by MukulAmbulgekar** [comment]
I think, the correct magic link is - http://docs.marklogic.com/guide/copyright/legal

I think, there are two issues here -

1. After the 'PDF-only product notices' change, the above link should not even be accessible (should throw error 404), but right now it's accessible on prod app. And, it's serving old product notices (9.0-2). This is because, I guess old product-notices document is still present in the DB , we may need to remove that first (`/apidoc/9.0/guide/copyright/legal.xml`).

2. The magic link should continue to work/redirect to the correct product notices, that you already mentioned above.

**Comment by kcoleman-marklogic** [comment]
The original link MUST continue to work. The fact that it is serving up some old cruft from 9.0-2 right now is basically a red herring. (I already ran around that bush several times with Jane and Tanya S.) 

I mean, yes, we could/should remove the dead file, but if the magic link was redirecting to the new URL, it wouldn't matter that the dead file is in the db. Removing the dead file fixes nothing. The rewriter needs to be changed. 

I think I have a fix, but SSH is being a pain in my backside right now, so I can't push the change to docapp. Therefore, it can't be reviewed by someone who actually understands what they're doing. Sigh.

**Comment by MukulAmbulgekar** [comment]
>but if the magic link was redirecting to the new URL, it wouldn't matter that the dead file is in the db

Currently, it doesn't redirect. I meant as a fix we could do that. However I Agree, changing rewriter is a better option.

**Comment by kcoleman-marklogic** [comment]
Fix has been merged to master, deployed, and approved by the stakeholder.
